apiVersion: v1
kind: Pod
metadata:
  name: oversized-pod
  namespace: resource-demo
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "600m"
          memory: "300Mi"
        limits:
          cpu: "700m"
          memory: "400Mi"
